name: music_theory
description: A chord analyzer
# version: 1.0.0
#homepage: https://www.kalaskod.se/music_theory
#author: Mikael Andersson

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  event_bus: ^1.1.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.9.3
  js: ^0.6.1+1
